name: Build and publish image

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
        default: 'main'

  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
  
jobs:
  build-and-push-image:
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-image.yml@main
    with:
      gitRef: ${{ inputs.gitRef || github.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GOVUK_ECR_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GOVUK_ECR_SECRET_ACCESS_KEY }}
