name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
      - ".git**"
      - README.md
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write
  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main
  test:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - run: make generate
      - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
         version: v2.4.0
         # caching issues, see: https://github.com/golangci/golangci-lint-action/issues/244#issuecomment-1052190775
         skip-cache: true
      - run: make test
        env:
          GOEXPERIMENT: loopvar
